// args= ['boards/make-pins.py', '--board', 'boards/lpx54608/pins.csv', '--af', 'boards/lpc54608_af.csv', '--prefix', 'boards/lpc546xx_prefix.c', '--hdr', 'build-lpx54608/genhdr/pins.h', '--qstr', 'build-lpx54608/pins_qstr.h', '--af-const', 'build-lpx54608/genhdr/pins_af_const.h', '--af-py', 'build-lpx54608/pins_af.py']
// This file was automatically generated by make-pins.py
//
// --af boards/lpc54608_af.csv
// --board boards/lpx54608/pins.csv
// --prefix boards/lpc546xx_prefix.c

// <MCU>_prefix.c becomes the initial portion of the generated pins file.

#include <stdio.h>

#include "py/obj.h"
#include "py/mphal.h"
#include "pin.h"

#define AF(af_idx, af_fn, af_unit, af_type, af_ptr) \
{ \
    { &pin_af_type }, \
    .name = MP_QSTR_AF ## af_idx ## _ ## af_fn ## af_unit, \
    .idx = (af_idx), \
    .fn = AF_FN_ ## af_fn, \
    .unit = (af_unit), \
    .type = AF_PIN_TYPE_ ## af_fn ## _ ## af_type, \
    .af_fn = (af_ptr) \
}

#define PIN(p_port, p_pin, p_af, p_adc_num, p_adc_channel) \
{ \
    { &pin_type }, \
    .name = MP_QSTR_ ## p_port ## p_pin, \
    .port = PORT_ ## p_port, \
    .pin = (p_pin), \
    .num_af = (sizeof(p_af) / sizeof(pin_af_obj_t)), \
    .pin_mask = (1 << ((p_pin) & 0x0f)), \
    .gpio = GPIO ## p_port, \
    .af = p_af, \
    .adc_num = p_adc_num, \
    .adc_channel = p_adc_channel, \
}

const pin_af_obj_t pin_314_af[] = {
  AF( 0, GPIO    ,  3, PIN14     , GPIO3   ), // GPIO3_PIN14
  //( 1, SCT     ,  0, OUT4      , SCT0    ), // SCT0_OUT4
  //( 2, FC      ,  9, RTS_SCL_SSEL1, FC9     ), // FC9_RTS_SCL_SSEL1
  //( 3, CTIMER  ,  3, MAT1      , CTIMER3 ), // CTIMER3_MAT1
};

const pin_obj_t pin_314 = PIN(3, 14, pin_314_af, PIN_ADC1 | PIN_ADC2 | PIN_ADC3, 0);

const pin_af_obj_t pin_33_af[] = {
  AF( 0, GPIO    ,  0, PIN3      , GPIO0   ), // GPIO0_PIN3
  //( 1, LCD     ,  0, VD17      , LCD     ), // LCD_VD17
  //( 2, FC      ,  9, TXD_SCL_MISO, FC9     ), // FC9_TXD_SCL_MISO
};

const pin_obj_t pin_33 = PIN(3, 3, pin_33_af, PIN_ADC1 | PIN_ADC2 | PIN_ADC3, 1);

const pin_af_obj_t pin_22_af[] = {
  AF( 0, GPIO    ,  0, PIN2      , GPIO0   ), // GPIO0_PIN2
  //( 1, ENET    ,  0, CRS       , ENET    ), // ENET_CRS
  //( 2, FC      ,  3, SSEL3     , FC3     ), // FC3_SSEL3
};

const pin_obj_t pin_22 = PIN(2, 2, pin_22_af, PIN_ADC1 | PIN_ADC2 | PIN_ADC3, 2);

const pin_af_obj_t pin_06_af[] = {
  AF( 0, GPIO    ,  0, PIN6      , GPIO0   ), // GPIO0_PIN6
  //( 1, FC      ,  3, SCK       , FC3     ), // FC3_SCK
  AF( 2, CTIMER  ,  3, CAP1      , CTIMER3 ), // CTIMER3_CAP1
  //( 3, CTIMER  ,  4, MAT0      , CTIMER4 ), // CTIMER4_MAT0
  //( 4, SCT     ,  0, GPI6      , SCT0    ), // SCT0_GPI6
  //( 6, EMC     ,  0, D4        , EMC     ), // EMC_D4
  //( 7, ENET    ,  0, RX_DV     , ENET    ), // ENET_RX_DV
  //(11, ISP     ,  2,           , ISP2    ), // ISP2
};

const pin_obj_t pin_06 = PIN(0, 6, pin_06_af, 0, 0);

const pin_af_obj_t pin_05_af[] = {
  AF( 0, GPIO    ,  0, PIN5      , GPIO0   ), // GPIO0_PIN5
  //( 1, CAN     ,  0, TD        , CAN0    ), // CAN0_TD
  //( 2, FC      ,  4, RXD_SDA_MOSI, FC4     ), // FC4_RXD_SDA_MOSI
  //( 3, CTIMER  ,  3, MAT0      , CTIMER3 ), // CTIMER3_MAT0
  //( 4, SCT     ,  0, GPI5      , SCT0    ), // SCT0_GPI5
  //( 6, EMC     ,  0, D3        , EMC     ), // EMC_D3
  //( 7, ENET    ,  0, MDIO      , ENET    ), // ENET_MDIO
  //(11, ISP     ,  1,           , ISP1    ), // ISP1
};

const pin_obj_t pin_05 = PIN(0, 5, pin_05_af, 0, 0);

const pin_af_obj_t pin_04_af[] = {
  AF( 0, GPIO    ,  0, PIN4      , GPIO0   ), // GPIO0_PIN4
  //( 1, CAN     ,  0, RD        , CAN0    ), // CAN0_RD
  //( 2, FC      ,  4, SCK       , FC4     ), // FC4_SCK
  AF( 3, CTIMER  ,  3, CAP0      , CTIMER3 ), // CTIMER3_CAP0
  //( 4, SCT     ,  0, GPI4      , SCT0    ), // SCT0_GPI4
  //( 6, EMC     ,  0, D2        , EMC     ), // EMC_D2
  //( 7, ENET    ,  0, MDC       , ENET    ), // ENET_MDC
  //(11, ISP     ,  0,           , ISP0    ), // ISP0
};

const pin_obj_t pin_04 = PIN(0, 4, pin_04_af, 0, 0);

STATIC const mp_rom_map_elem_t pin_cpu_pins_locals_dict_table[] = {
  { MP_ROM_QSTR(MP_QSTR_314), MP_ROM_PTR(&pin_314) },
  { MP_ROM_QSTR(MP_QSTR_33), MP_ROM_PTR(&pin_33) },
  { MP_ROM_QSTR(MP_QSTR_22), MP_ROM_PTR(&pin_22) },
  { MP_ROM_QSTR(MP_QSTR_06), MP_ROM_PTR(&pin_06) },
  { MP_ROM_QSTR(MP_QSTR_05), MP_ROM_PTR(&pin_05) },
  { MP_ROM_QSTR(MP_QSTR_04), MP_ROM_PTR(&pin_04) },
};
MP_DEFINE_CONST_DICT(pin_cpu_pins_locals_dict, pin_cpu_pins_locals_dict_table);

STATIC const mp_rom_map_elem_t pin_board_pins_locals_dict_table[] = {
  { MP_ROM_QSTR(MP_QSTR_LED1), MP_ROM_PTR(&pin_314) },
  { MP_ROM_QSTR(MP_QSTR_LED2), MP_ROM_PTR(&pin_22) },
  { MP_ROM_QSTR(MP_QSTR_LED3), MP_ROM_PTR(&pin_33) },
  { MP_ROM_QSTR(MP_QSTR_SW2), MP_ROM_PTR(&pin_06) },
  { MP_ROM_QSTR(MP_QSTR_SW3), MP_ROM_PTR(&pin_05) },
  { MP_ROM_QSTR(MP_QSTR_SW4), MP_ROM_PTR(&pin_04) },
};
MP_DEFINE_CONST_DICT(pin_board_pins_locals_dict, pin_board_pins_locals_dict_table);

const pin_obj_t * const pin_adc1[] = {
  &pin_314, // 0
  &pin_33, // 1
  &pin_22, // 2
  NULL,    // 3
  NULL,    // 4
  NULL,    // 5
  NULL,    // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
#if defined(MCU_SERIES_L4)
  NULL,    // 16
#endif
};

const pin_obj_t * const pin_adc2[] = {
  &pin_314, // 0
  &pin_33, // 1
  &pin_22, // 2
  NULL,    // 3
  NULL,    // 4
  NULL,    // 5
  NULL,    // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
#if defined(MCU_SERIES_L4)
  NULL,    // 16
#endif
};

const pin_obj_t * const pin_adc3[] = {
  &pin_314, // 0
  &pin_33, // 1
  &pin_22, // 2
  NULL,    // 3
  NULL,    // 4
  NULL,    // 5
  NULL,    // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
#if defined(MCU_SERIES_L4)
  NULL,    // 16
#endif
};
