    { MP_OBJ_NEW_QSTR(MP_QSTR_AF0_GPIO0),   MP_OBJ_NEW_SMALL_INT(GPIO_AF0_GPIO0) },
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF0_GPIO3),   MP_OBJ_NEW_SMALL_INT(GPIO_AF0_GPIO3) },
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF2_CTIMER3), MP_OBJ_NEW_SMALL_INT(GPIO_AF2_CTIMER3) },
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF3_CTIMER3), MP_OBJ_NEW_SMALL_INT(GPIO_AF3_CTIMER3) },
